root = "/app"
tmp_dir = "/tmp/air-consumer"

[build]
cmd = "go build -buildvcs=false -o /tmp/air-consumer/consumer ./cmd/consumer"
bin = "/tmp/air-consumer/consumer"
include_ext = ["go"]
exclude_dir = [".git", "tmp", "vendor"]
delay = 300
kill_delay = 500
stop_on_error = true
send_interrupt = true

[log]
time = true
